title = "tishmen.io"
theme = "coder"

[params]
    author = "Milan Topuzov"
    description = "Milan Topuzov - Python dev and big data enthusiast"
    keywords = "blog,developer,personal"
    info = "Python dev and big data enthusiast"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/tishmen/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/milan_topuzov"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/milan-topuzov/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
